// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3wqvanjz23oM3E22-hXVCmNwYjSAstLk',
    appId: '1:396949570415:web:b470fc8bb729bef20c5e9a',
    messagingSenderId: '396949570415',
    projectId: 'storageapp-2439a',
    authDomain: 'storageapp-2439a.firebaseapp.com',
    storageBucket: 'storageapp-2439a.appspot.com',
    measurementId: 'G-2G6HHP2KZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDIdaQIUBqYofi06G1ihJ_yxc8JzBi7-k',
    appId: '1:396949570415:android:4858514ebf5b6d4d0c5e9a',
    messagingSenderId: '396949570415',
    projectId: 'storageapp-2439a',
    storageBucket: 'storageapp-2439a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1pYpfrii5G1xuuLIPDQCcr0EGOgOL5dQ',
    appId: '1:396949570415:ios:cfc96db41c6b04020c5e9a',
    messagingSenderId: '396949570415',
    projectId: 'storageapp-2439a',
    storageBucket: 'storageapp-2439a.appspot.com',
    iosBundleId: 'com.example.docupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1pYpfrii5G1xuuLIPDQCcr0EGOgOL5dQ',
    appId: '1:396949570415:ios:cfc96db41c6b04020c5e9a',
    messagingSenderId: '396949570415',
    projectId: 'storageapp-2439a',
    storageBucket: 'storageapp-2439a.appspot.com',
    iosBundleId: 'com.example.docupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3wqvanjz23oM3E22-hXVCmNwYjSAstLk',
    appId: '1:396949570415:web:208c0f3b20054a7c0c5e9a',
    messagingSenderId: '396949570415',
    projectId: 'storageapp-2439a',
    authDomain: 'storageapp-2439a.firebaseapp.com',
    storageBucket: 'storageapp-2439a.appspot.com',
    measurementId: 'G-FWB0QVR8NJ',
  );
}
